# -*- coding: utf-8 -*-
"""PricePredict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sZG2FoLQmeeYmQBZwzKbiycEhSc7UGvi
"""

#Importing
import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
from sklearn.linear_model import LinearRegression
import numpy as np

path  = '/Mobile-Price-Prediction-cleaned_data.csv'
price_data = pd.read_csv(path)
print(price_data.head(10))

data = pd.DataFrame(price_data)

#sns.scatterplot(x = 'Ratings', y = 'Price', data = price_data)

x = price_data[['Battery_Power','Ratings','RAM','ROM','Mobile_Size','Primary_Cam','Selfi_Cam']]
y = price_data['Price']
lin = LinearRegression()
lin.fit(x,y)
y_pred = lin.predict(x)

plot = LinearRegression(fit_intercept = True)
plot.fit(x,y)
#prints the accuracy of this model
print(plot.score(x, y)*100)
#The very first model (Linear Regression) proves to be inaccurate for this dataset.